edition: 1.0.0
name: web-framework-app
access: "{{ access }}"

vars:
  service:
    name: "{{ serviceName }}"
    description: '快速部署PaddleOCR 项目地址 https://github.com/duolabmeng6/paddlehub_ppocr'

services:
  framework:
    component: fc
    props:
      region: "{{ region }}"
      service:
        name: ${vars.service.name}
        description: ${vars.service.description}
        internetAccess: true
        role:
          name: paddleocrrole
          policies:
            - AliyunContainerRegistryReadOnlyAccess
      function:
        name: "{{ functionName }}"
        description: ${vars.service.description}
        runtime: custom-container
        memorySize: 2048
        caPort: 9000
        codeUri: ./
        timeout: 60
        customContainerConfig:
          image: registry-vpc.cn-shenzhen.aliyuncs.com/duolabmeng/ppocr:1.8
          command: '["sh","/PaddleOCR/start.sh"]'
        environmentVariables:
          testEnv: true
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
